# Generated by Django 4.1.6 on 2024-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="deleted",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
