# Generated by Django 4.1.6 on 2024-02-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0002_alter_branch_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="name of brand in product", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="name of category in product", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("barcode", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/products"
                    ),
                ),
                ("price_sale", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_buy", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observation", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "iva",
                    models.IntegerField(
                        default=21, help_text="no is required, but default is 21%"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("stock", models.PositiveBigIntegerField(default=2)),
                ("stock_min", models.PositiveBigIntegerField(default=1)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.subcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbranch",
            constraint=models.UniqueConstraint(
                models.F("product"), models.F("branch"), name="product_branch_unique"
            ),
        ),
    ]
