version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: >
                bash -c "python manage.py makemigrations --settings=sgventas.settings.develop &&
                            python manage.py migrate --settings=sgventas.settings.develop &&
                            python manage.py runserver 0.0.0.0:8000 --settings=sgventas.settings.develop"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A sgventas worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    flower:
        image: mher/flower:0.9.7
        command: [ 'flower', '--broker=redis://redis:6379/0', '--port=5555' ]
        expose:
            - 5555
        ports:
            - "5555:5555"
        depends_on:
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=sg_sales
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
        expose:
            - 5432
        ports:
            - "5432:5432"
    redis:
        image: "redis:alpine"

volumes:
    pgdata: