version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./compose/production/django/Dockerfile
        container_name: backend-web
        command: >
          bash -c "python manage.py migrate --settings=sgventas.settings.production &&
                      gunicorn sgventas.wsgi:application --bind 0.0.0.0:8000"
        volumes:
          - static_volume:/home/backend/web/staticfiles
        expose:
          - 8000
        ports:
          - "8000:8000"
        environment:
          - DEBUG=0
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis

    celery:
        build: .
        command: celery -A sgventas worker -l INFO
        volumes:
          - .:/usr/src/app
        environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
          - web
          - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=sg_sales
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
        expose:
            - 5432
        ports:
            - "5432:5432"
    nginx:
        build:
            context: .
            dockerfile: ./compose/production/nginx/Dockerfile
        container_name: backend-proxy
        volumes:
          - static_volume:/staticfiles
        ports:
          - 1337:80
        depends_on:
          - web
    redis:
        image: "redis:alpine"

volumes:
  pgdata:
  static_volume: