# Generated by Django 4.1.6 on 2024-02-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("branches", "0002_alter_branch_deleted"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("date_sale", models.DateField(auto_now_add=True)),
                ("hour_sale", models.TimeField(auto_now_add=True)),
                (
                    "type_payment",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit"),
                            ("CREDIT", "Credit"),
                            ("CASH", "Cash"),
                            ("TRANSFER", "transfer"),
                        ],
                        default="CASH",
                        max_length=30,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DetailSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.DateTimeField(blank=True, default=None, null=True)),
                ("amount", models.PositiveBigIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.sale"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
