# Generated by Django 4.1.6 on 2024-01-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_sale_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="type_payment",
            field=models.CharField(
                choices=[
                    ("DEBIT", "Debit"),
                    ("CREDIT", "Credit"),
                    ("CASH", "Cash"),
                    ("TRANSFER", "transfer"),
                ],
                default="CASH",
                max_length=30,
            ),
        ),
    ]
